

services:
  frontend:
    build: ./frontend
    image: ${ECR_REGISTRY}/${ECR_REPO}:frontend-${IMAGE_TAG}
    ports:
      - "80:80"
    networks:
      - frontend-net
    depends_on:
      - backend

  backend:
    build: ./backend
    image: ${ECR_REGISTRY}/${ECR_REPO}:backend-${IMAGE_TAG}
    ports:
      - "5000:5000"
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_SECRET_NAME=prod/myapp/secrets
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
      - DB_NAME=staff_db
      - REDIS_HOST=redis
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    networks:
      - backend-net

  postgres:
    image: postgres:15
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_SECRET_NAME=prod/myapp/secrets
    volumes:
      # Keep the existing data volume
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  frontend-net:
  backend-net:

